#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-stringi
Version  : 1.7.12
Release  : 106
URL      : https://cran.r-project.org/src/contrib/stringi_1.7.12.tar.gz
Source0  : https://cran.r-project.org/src/contrib/stringi_1.7.12.tar.gz
Summary  : Fast and Portable Character String Processing Facilities
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: R-stringi-lib = %{version}-%{release}
Requires: R-stringi-license = %{version}-%{release}
BuildRequires : buildreq-R
BuildRequires : pkgconfig(icu-uc)

%description
processing tools for pattern searching (e.g., with 'Java'-like regular
    expressions or the 'Unicode' collation algorithm), random string generation,
    case mapping, string transliteration, concatenation, sorting, padding,
    wrapping, Unicode normalisation, date-time formatting and parsing,
    and many more. They are fast, consistent, convenient, and -
    thanks to 'ICU' (International Components for Unicode) -
    portable across all locales and platforms. Documentation about 'stringi' is

%package lib
Summary: lib components for the R-stringi package.
Group: Libraries
Requires: R-stringi-license = %{version}-%{release}

%description lib
lib components for the R-stringi package.


%package license
Summary: license components for the R-stringi package.
Group: Default

%description license
license components for the R-stringi package.


%prep
%setup -q -n stringi
cd %{_builddir}/stringi

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1678830977

%install
export SOURCE_DATE_EPOCH=1678830977
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-stringi
cp %{_builddir}/stringi/LICENSE %{buildroot}/usr/share/package-licenses/R-stringi/1ab0eaec0a648aa3295c169f352c0257dd880502 || :
cp %{_builddir}/stringi/src/icu55/license.html %{buildroot}/usr/share/package-licenses/R-stringi/02ae9e6d4574c1e9c99b264fbcb08efcb1b8e3d9 || :
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/stringi/AUTHORS
/usr/lib64/R/library/stringi/CITATION
/usr/lib64/R/library/stringi/DESCRIPTION
/usr/lib64/R/library/stringi/INDEX
/usr/lib64/R/library/stringi/LICENSE
/usr/lib64/R/library/stringi/Meta/Rd.rds
/usr/lib64/R/library/stringi/Meta/features.rds
/usr/lib64/R/library/stringi/Meta/hsearch.rds
/usr/lib64/R/library/stringi/Meta/links.rds
/usr/lib64/R/library/stringi/Meta/nsInfo.rds
/usr/lib64/R/library/stringi/Meta/package.rds
/usr/lib64/R/library/stringi/NAMESPACE
/usr/lib64/R/library/stringi/NEWS
/usr/lib64/R/library/stringi/R/stringi
/usr/lib64/R/library/stringi/R/stringi.rdb
/usr/lib64/R/library/stringi/R/stringi.rdx
/usr/lib64/R/library/stringi/help/AnIndex
/usr/lib64/R/library/stringi/help/aliases.rds
/usr/lib64/R/library/stringi/help/paths.rds
/usr/lib64/R/library/stringi/help/stringi.rdb
/usr/lib64/R/library/stringi/help/stringi.rdx
/usr/lib64/R/library/stringi/html/00Index.html
/usr/lib64/R/library/stringi/html/R.css
/usr/lib64/R/library/stringi/include/stringi.cpp
/usr/lib64/R/library/stringi/include/stringi.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/stringi/libs/stringi.so
/usr/lib64/R/library/stringi/libs/stringi.so.avx2
/usr/lib64/R/library/stringi/libs/stringi.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-stringi/02ae9e6d4574c1e9c99b264fbcb08efcb1b8e3d9
/usr/share/package-licenses/R-stringi/1ab0eaec0a648aa3295c169f352c0257dd880502
