#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-stringi
Version  : 0.4
Release  : 5
URL      : http://cran.r-project.org/src/contrib/stringi_0.4-1.tar.gz
Source0  : http://cran.r-project.org/src/contrib/stringi_0.4-1.tar.gz
Summary  : Character String Processing Facilities
Group    : Development/Tools
License  : BSD-3-Clause ICU
BuildRequires : clr-R-helpers
BuildRequires : pkgconfig(icu-uc)

%description
No detailed description available

%prep
%setup -q -c -n stringi

%build

%install
rm -rf %{buildroot}
export LANG=C
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --build  -l %{buildroot}/usr/lib64/R/library stringi
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library stringi


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/stringi/AUTHORS
/usr/lib64/R/library/stringi/CITATION
/usr/lib64/R/library/stringi/DESCRIPTION
/usr/lib64/R/library/stringi/INDEX
/usr/lib64/R/library/stringi/LICENSE
/usr/lib64/R/library/stringi/Meta/Rd.rds
/usr/lib64/R/library/stringi/Meta/hsearch.rds
/usr/lib64/R/library/stringi/Meta/links.rds
/usr/lib64/R/library/stringi/Meta/nsInfo.rds
/usr/lib64/R/library/stringi/Meta/package.rds
/usr/lib64/R/library/stringi/NAMESPACE
/usr/lib64/R/library/stringi/NEWS
/usr/lib64/R/library/stringi/R/stringi
/usr/lib64/R/library/stringi/R/stringi.rdb
/usr/lib64/R/library/stringi/R/stringi.rdx
/usr/lib64/R/library/stringi/help/AnIndex
/usr/lib64/R/library/stringi/help/aliases.rds
/usr/lib64/R/library/stringi/help/paths.rds
/usr/lib64/R/library/stringi/help/stringi.rdb
/usr/lib64/R/library/stringi/help/stringi.rdx
/usr/lib64/R/library/stringi/html/00Index.html
/usr/lib64/R/library/stringi/html/R.css
/usr/lib64/R/library/stringi/libs/stringi.so
/usr/lib64/R/library/stringi/libs/symbols.rds
